language: node_js
node_js:
   - "0.12"
   - "0.11"
   - "0.10"
before_script:
   - npm install -g grunt-cli
   - echo "interfaces"
   - ifconfig -a
   - npm start &
before_install:
   - sudo apt-get install libpcap-dev